[build-system]
requires = ["setuptools", "wheel", "numpy", "cython"]
build-backend = "setuptools.build_meta"

[project]
name = "uavarprior"
version = "0.1.0-dev"
dynamic = [
    "description",
    "readme",
    "classifiers",
    "dependencies",
    "scripts"
]
