[build-system]
requires = ["setuptools>=61.0", "wheel", "numpy>=1.24.0", "cython>=0.29.0"]
build-backend = "setuptools.build_meta"

[project]
name = "uavarprior"
version = "0.1.0"
description = "Uncertainty-Aware Variational Prior framework for deep learning"
readme = "README.md"
license = {text = "BSD-3-Clause"}
authors = [
    {name = "Your Name", email = "your.email@domain.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Bio-Informatics"
]
requires-python = ">=3.8"
dependencies = [
    "click>=8.0",
    "cython>=0.29.0",
    "h5py>=3.6.0",
    "matplotlib>=3.5.0",
    "numpy>=1.24.0",
    "pandas>=1.4.0",
    "plotly>=5.0.0",
    "pyfaidx>=0.7.0",
    "PyYAML>=6.0",
    "scikit-learn>=1.1.0",
    "scipy>=1.9.0",
    "seaborn>=0.11.0",
    "statsmodels>=0.13.0",
    "torch>=1.12.0",
    "biopython>=1.79"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "black>=22.0",
    "isort>=5.10",
    "flake8>=5.0",
    "mypy>=0.991",
    "pre-commit>=2.20"
]
docs = [
    "sphinx>=5.0",
    "sphinx-rtd-theme>=1.0",
    "myst-parser>=0.18"
]

[project.scripts]
uavarprior = "uavarprior.cli:main"

[project.urls]
Homepage = "https://github.com/SanjeevaRDodlapati/UAVarPrior"
Documentation = "https://github.com/SanjeevaRDodlapati/UAVarPrior/docs"
Repository = "https://github.com/SanjeevaRDodlapati/UAVarPrior"
Issues = "https://github.com/SanjeevaRDodlapati/UAVarPrior/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"uavarprior.interpret" = ["data/**/*"]
"uavarprior.sequences" = ["data/*"]

[tool.black]
line-length = 88
target-version = ['py38', 'py39', 'py310', 'py311']

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--strict-markers --disable-warnings"

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
