---
ops: [analyze]
model: {
 #   path: ., # there is no need to specify path for built-in networks under nn pacakge
#    class: SeqCnnL2h128,
    class: DeepSEA,
    classArgs: {  # DeeperDeepSEA.__init__ inputs
        sequence_length: 1001,
        n_targets: 1,
        l1_decay: 0.0001,
        l2_decay: 0.0001,
        dropout: 0,
        batch_norm: False,
    },
    built: pytorch, #pytorch or tensorflow
    mult_predictions: 100,
    wrapper: UniSeqMWrapper,
#    non_strand_specific: mean
}
analyzer: !obj:fugep.predict.MethylVarEvaluator {
    analysis: [abs_diffs, std], #[diffs, abs_diffs, logits, predictions],
    refSeq: !obj:fugep.data.Genome {
        input_path: /Users/sanjeev/Downloads/debug/GRCh38/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    },
#    genAssembly: ncbi,
    vcfFile: /Users/sanjeev/Downloads/debug/fugep/data/samp_vcf_100.tsv,
    cpgFile: /Users/sanjeev/Downloads/debug/fugep/data/refCpGHumGRCh38.tsv,
    strandIdx: 5,
    seqLen: 1001,
    batchSize: 16,
    useCuda: False,
    dataParallel: True,
    loggingVerbosity: 2,
    writeMemLimit: 10, # in MB
    outputFormat: hdf5, # tsv, #
    trainedModelPath: /Users/sanjeev/Downloads/debug/fugep/model/dna-met/best_model.pth.tar,
#    trainedModelPath: /Users/sanjeev/Downloads/debug/fugep/model/dna-met/model.h5,
    features: !obj:fugep.utils.load_features_list {
        input_path: /Users/sanjeev/Downloads/debug/fugep/model/dna-met/features.txt
    },

}
variant_effect_prediction: {}
output_dir: /Users/sanjeev/Downloads/debug/fugep/gve/met_temp
random_seed: 1447 # seed torch
create_subdirectory: False
...
