---
ops: [train]
model: {
 #   path: ., # there is no need to specify path for built-in networks under nn pacakge
    class: Sei,
#    classArgs: {  # DeeperDeepSEA.__init__ inputs
#        sequence_length: 2001,
#        n_targets: 10
#    },
    built: pytorch,
    mult_predictions: 1,
    wrapper: UniSeqMWrapper,
      #non_strand_specific: mean
}
sampler: !obj:fugep.samplers.MethylH5Sampler {
    h5FileDir: /scratch/ml-csm/projects/fgenom/dna-met/hum_brain/data/fugep_input_4k,
    train: [c1, c4, c7, c10, c13, c16, c19, c22],
    validate: [c3, c6, c9, c12, c15, c18, c21],
    batchSize: 128,
      #test: [c2, c5, c8, c11, c14, c17, c20],
    unpackSeq: True,
    unpackTarget: False,
    mode: train,
    weightSampByCls: True,
    valOfMisInTarget: -1,
    seed: 1447,
    nWorkers: 0,
 #   features: !obj:fugep.utils.load_features_list {
 #       input_path: /data/hpc/projects/fgenom/ocl/train-data/rmdnase/hg19/debug/h5/data/distinct_features.txt
 #   }
}
train_model: !obj:fugep.train.StandardSGDTrainer {
    batchSize: 128,
    maxNSteps: 4,
    nStepsStatReport: 2,
    nStepsCheckpoint: 1,
    transferAndTune: /home/sdodl001/sei-framework/model/sei.pth,
    newClassifier: True,
    freezeStem: True,
    nValidationSamples: 2000, # if not specified, all examples from validation set will be used
      #nTestSamples: 512, # if not specified, all examples from test set will be used
    useCuda: True,
    dataParallel: True,
    nMinMinorsReport: 1, # the minimum number of examples of minor class a feature to have to be included in the performance report
    loggingVerbosity: 1,
    preloadValData: False,
    preloadTestData: False,
}

output_dir: /scratch/ml-csm/projects/fgenom/dna-met/hum_brain/models/sei_ft_frzStm/lr0.05_test
lr: 0.05
random_seed: 1447 # seed torch
create_subdirectory: False
...
