ops: [analyze]

model:
  name: Sei
  class: Sei
  classArgs:
    sequence_length: 4096
    n_targets: 21907
  built: pytorch
  mult_predictions: 5
  wrapper: UniSeqMWrapper
  non_strand_specific: mean

analyzer: !obj:uavarprior.predict.PeakGVarEvaluator
  analysis:
    - mean_gve
    - pval
  seqLen: 4096
  batchSize: 64
  useCuda: false
  dataParallel: true
  loggingVerbosity: 0
  writeMemLimit: 500
  save_mult_pred: true
  outputFormat: tsv

variant_effect_prediction: {}
output_dir: /tmp/test-analyze
random_seed: 1447
create_subdirectory: false
