ops: [analyze]  # Use legacy format with ops list containing analyze operation

model:
  name: Sei
  class: Sei
  classArgs:
    sequence_length: 4096
    n_targets: 21907
  built: pytorch
  mult_predictions: 5
  wrapper: UniSeqMWrapper
  non_strand_specific: mean

# Note we're using the !obj tag syntax directly
analyzer: !obj:uavarprior.predict.PeakGVarEvaluator
  analysis:
    - mean_gve
  trainedModelPath: /home/sdodl001/sei-framework/sei.pth

variant_effect_prediction: {}  # Needed to trigger variant effect prediction
output_dir: /tmp/test-analyze-output  # Use a temporary directory for testing
random_seed: 1447
